keycloak:
    auth-server-url: http://134.119.192.94:8080/auth
    bearer-only: true
    credentials:
        secret: AEJX11epl18scTstFzk0zvbnJ7smxo6I
    principal-attribute: preferred_username
    realm: datagreen
    resource: dg-server
    ssl-required: external
    use-resource-role-mappings: true
spring:
    main:
        allow-bean-definition-overriding: true
